# coding: utf-8

"""
    ClinicalTrials.gov REST API

    This API is made available to provide users meta data, statistics, and the most recent version of the clinical trials available on ClinicalTrials.gov.

    The version of the OpenAPI document: 2.0.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clinicaltrials.models.derived_section import DerivedSection

class TestDerivedSection(unittest.TestCase):
    """DerivedSection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DerivedSection:
        """Test DerivedSection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DerivedSection`
        """
        model = DerivedSection()
        if include_optional:
            return DerivedSection(
                misc_info_module = clinicaltrials.models.misc_info_module.MiscInfoModule(
                    version_holder = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    removed_countries = [
                        ''
                        ], 
                    submission_tracking = clinicaltrials.models.submission_tracking.SubmissionTracking(
                        estimated_results_first_submit_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        first_mcp_info = clinicaltrials.models.first_mcp_info.FirstMcpInfo(
                            post_date_struct = clinicaltrials.models.date_struct.DateStruct(
                                date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                type = 'ACTUAL', ), ), 
                        submission_infos = [
                            clinicaltrials.models.submission_info.SubmissionInfo(
                                release_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                unrelease_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                unrelease_date_unknown = True, 
                                reset_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                mcp_release_n = 56, )
                            ], ), ),
                condition_browse_module = clinicaltrials.models.browse_module.BrowseModule(
                    meshes = [
                        clinicaltrials.models.mesh.Mesh(
                            id = '', 
                            term = '', )
                        ], 
                    ancestors = [
                        clinicaltrials.models.mesh.Mesh(
                            id = '', 
                            term = '', )
                        ], 
                    browse_leaves = [
                        clinicaltrials.models.browse_leaf.BrowseLeaf(
                            id = '', 
                            name = '', 
                            as_found = '', 
                            relevance = 'LOW', )
                        ], 
                    browse_branches = [
                        clinicaltrials.models.browse_branch.BrowseBranch(
                            abbrev = '', 
                            name = '', )
                        ], ),
                intervention_browse_module = clinicaltrials.models.browse_module.BrowseModule(
                    meshes = [
                        clinicaltrials.models.mesh.Mesh(
                            id = '', 
                            term = '', )
                        ], 
                    ancestors = [
                        clinicaltrials.models.mesh.Mesh(
                            id = '', 
                            term = '', )
                        ], 
                    browse_leaves = [
                        clinicaltrials.models.browse_leaf.BrowseLeaf(
                            id = '', 
                            name = '', 
                            as_found = '', 
                            relevance = 'LOW', )
                        ], 
                    browse_branches = [
                        clinicaltrials.models.browse_branch.BrowseBranch(
                            abbrev = '', 
                            name = '', )
                        ], )
            )
        else:
            return DerivedSection(
        )
        """

    def testDerivedSection(self):
        """Test DerivedSection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
